// ── Cloudflare environment ────────────────────────────────────────────────────

export interface Env {
  // Bindings
  DB: D1Database;
  VAULT: R2Bucket;
  AI: Ai;
  CHAT_DO: DurableObjectNamespace;

  // Worker Loader binding — type generated by `wrangler types`
  LOADER: WorkerLoader;

  // Secrets (set via `wrangler secret put`)
  GOOGLE_AI_KEY: string;
  API_SECRET: string;
  TELEGRAM_BOT_TOKEN: string;
  TELEGRAM_ALLOWED_USER_ID: string;
  GOOGLE_CAL_CLIENT_EMAIL: string;
  GOOGLE_CAL_PRIVATE_KEY: string;
  GOOGLE_CALENDAR_ID: string;

  // Optional vars
  ENVIRONMENT?: string;
}

// ── Agent context ─────────────────────────────────────────────────────────────
// The unified context passed into the kernel and all tool executors.

export interface AgentContext {
  messages: StoredMessage[];
  platform: 'websocket' | 'telegram';
  metadata: Record<string, unknown>; // activeNote, chatId, etc.
}

// ── D1 row types ──────────────────────────────────────────────────────────────

export interface VaultFile {
  path: string;
  contentHash: string;
  updatedAt: number; // unix ms
  size: number;      // bytes
}

// ── Sync API payloads ─────────────────────────────────────────────────────────

export interface SyncManifestEntry {
  path: string;
  contentHash: string;
  updatedAt: number;
  size: number;
}

export interface ManifestRequest {
  files: SyncManifestEntry[];
}

export interface ManifestResponse {
  toUpload: string[];
  toDownload: VaultFile[];
}

export interface BatchDownloadRequest {
  paths: string[];
}

export interface DownloadedFile {
  path: string;
  content: string;
  contentHash: string;
  updatedAt: number;
  size: number;
}

export interface BatchDownloadResponse {
  files: DownloadedFile[];
}

export interface DeleteRequest {
  deletions: { path: string; deletedAt: number }[];
}

export interface Tombstone {
  path: string;
  deletedAt: number;
}

// ── Agent / search types ──────────────────────────────────────────────────────

export interface SearchResult {
  filename: string;
  score: number;
  link: string;
  excerpt: string;
}

// ── Durable Object storage ────────────────────────────────────────────────────

export interface StoredMessage {
  role: 'user' | 'assistant';
  content: string;
  timestamp: number;
}

// ── WebSocket protocol ────────────────────────────────────────────────────────

export type WsIncoming =
  | { type: 'message'; content: string; activeNote?: string }
  | { type: 'stop' };

export type WsOutgoing =
  | { type: 'ready'; sessionId: string }
  | { type: 'token'; content: string }
  | { type: 'thinkingToken'; content: string }
  | { type: 'thinkingDone' }
  | { type: 'toolCall'; name: string; args: unknown; label: string; reasoning: string | null }
  | { type: 'toolResult'; name: string; args: unknown; results: SearchResult[] }
  | { type: 'syncRequired' }
  | { type: 'done' }
  | { type: 'error'; message: string };